---
spring:
  application:
    name: youtube-search-api
  messages:
    encoding: UTF-8
  jackson:
    time-zone: "Asia/Tokyo"

logging:
  level:
    web: debug

# youtube
extension:
  youtube:
    # みこちのチャンネルIDを記載
    mikoChId: UC-hM6YJuNYVAmUWxeIr9FeA
    # すいせい
    suiseiChId: UC5CwaMl1eIgY8h02uZw7u8A
    # やしきず
    yashikizuChId : UCKMYISTJAQ8xTplUPHiABlA
    key: ${youtubeApiKey}

---
# -Dspring.profiles.activeを指定しなかった場合に実行される application.ymlの指定
spring:
  profiles:
    default: local